version: '3.0'

networks:
  mi-red:

services:

  eureka-server:
    build:
      context: eureka-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8761:8761
    networks:
      - mi-red

  zuul-server:
    build:
      context: zuul-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8090:8090
    networks:
      mi-red:
    depends_on:
      - eureka-server

  usuario-service:
    build:
      context: usuario-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8003:8003
    networks:
      mi-red:
    depends_on:
      - eureka-server

  productoservices:
    build: .
    restart: always
    ports:
      - 8009:8009
    networks:
      mi-red:
    depends_on:
      - eureka-server
      - usuario-service

  item-service:
    build:
      context: item-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8002:8002
    networks:
      mi-red:
    depends_on:
      - eureka-server
      - usuario-service
      - productoservices




